steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/cpsc324-project-452600/utr-scraper-repo/utr-scraper-image:latest', '.']
images:
  - 'us-west1-docker.pkg.dev/cpsc324-project-452600/utr-scraper-repo/utr-scraper-image:latest'
options:
  logging: CLOUD_LOGGING_ONLY # or REGIONAL_USER_OWNED_BUCKET or NONE
  machineType: 'N1_HIGHCPU_8'  # Optional: specify machine type if needed
timeout: 1200s  # Optional: specify a timeout (adjust as needed)
