steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/cpsc324-project-452600/utr-scraper-repo/utr-scraper-image:latest', '.']
images:
  - 'us-west1-docker.pkg.dev/cpsc324-project-452600/utr-scraper-repo/utr-scraper-image:latest'
options:
  logging: CLOUD_LOGGING_ONLY  
  machineType: 'E2_SMALL'  # Use e2-small to stay cost-effective
